### ISSUE TITLE
Error in data preperation for "preprocess_mars_image.py"

### ISSUE THREAD

**Issue by naziaperwaiz** [TuSimple/rl-multishot-reid#5]
For preparation of Mars data, following error is seen:
 Traceback (most recent call last):
  File "preprocess_mars_image.py", line 100, in <module>
    gen_train()
  File "preprocess_mars_image.py", line 85, in gen_train
    save_train(pool)
  File "preprocess_mars_image.py", line 46, in save_train
    ts = random.sample(pool, 96)
  File "/usr/lib/python2.7/random.py", line 323, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population

I have tried by reducing the sample size (ts = random.sample(pool, 96)) but the issue pertains. Do i need to change pool size? Any suggestion please?
Regards,

**Comment by SMCamila** [comment]
I think the reason is the pool variable is an empty list. Could you please check the dataset is well prepared and all the paths are correct?

**Comment by naziaperwaiz** [comment]
Many thanks for your response. Yes the issue was in dataset, re-downloading of dataset resolved that issue. Now i am having issue in updating im2rec folder.

The data lists are being prepared correctly in "recs" folder of respective datasets but im2rec folder is not being updated. I have updated the paths in preprocessing_files for im2rec i.e. "home/pc_name/virtualenv_name (i.e.mxnet)/bin/im2rec". What path is supposed to be given for im2rec? Am i giving the right path? 
Screen-shot of Mars and ilLIDS-VID preprocessing is attached for information please.

![preprocessing](https://user-images.githubusercontent.com/3807105/43988285-5bbc9ffc-9d4b-11e8-9134-c7ba87d0a527.png)
Regards,

**Comment by buaaswf** [comment]
I have the same issue
